services:
  node-api:
    container_name: node-api
    image: node-api:dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - node_api_modules:/app/node_modules
    ports:
      - 4444:4444
    command: npx ts-node --transpile-only ./src/app.ts
    restart: unless-stopped
    environment:
      NODE_ENV: development
      SERVER_PORT: 4444
      DB_DATABASE: node_api
      DB_CONNECTION_STRING: mysql://nodeapi_root:j5m966qp7jiypfda@node-api-mysql:3306/node_api
      LEGACY_LIST: ${LEGACY_LIST:-}
      DB_LOGGING: ${DB_LOGGING:-}
    networks:
      - node-api-connect
    depends_on:
      - node-api-mysql

  node-api-mysql:
    container_name: node-api-mysql
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_USER: nodeapi_root
      MYSQL_PASSWORD: j5m966qp7jiypfda
      MYSQL_ROOT_PASSWORD: m45ug42qkr5pdzbb
      MYSQL_DATABASE: node_api
    ports:
      - 3308:3306
    volumes:
      - ~/docker/volumes/NodeApi_MySQL:/var/lib/mysql
    networks:
      - node-api-connect
    logging:
      driver: none

networks:
  node-api-connect:
    name: node-api-connect

volumes:
  node_api_modules:
